apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: food-delivery
type: Opaque
data:
  # These are base64 encoded passwords
  USER_DB_PASSWORD: X3QlYkIpTmpENGVNNWZr
  RESTAURANT_DB_PASSWORD: YzhULy9aZGRIK2tTZnkr
  ORDER_DB_PASSWORD: eEQzamR2ZkY3dDFDSUhZaw==
  PAYMENT_DB_PASSWORD: ZEs0aHg/VXNNWXVEN0BL
  DELIVERY_DB_PASSWORD: X3QlYkIpTmpENGVNNWZr
  NOTIFICATION_DB_PASSWORD: ZEs0aHg/VXNNWXVEN0BL
  REDIS_PASSWORD: ""
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVJDdWxIUEVReFNhbUFQR1dzeDlKc2hYeHl0ZHRjRkdjckM4QTVqcGZ1UkJ6WTN1TFprMWE3Y0Noelk4djdVdmZ1RVRMamxtcDZXdTM5aGpETVZPUGZaNjAwaVpvamVvNjk=
  EMAIL_USERNAME: ""
  EMAIL_PASSWORD: ""
